name: CI

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13", "3.13t", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv and set up Python ${{ matrix.python-version }}
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
      - name: Install tox-uv
        run: uv tool install tox --with tox-uv
        env:
          UV_SYSTEM_PYTHON: 1

      - name: Run tests with tox-uv
        run: uv run --no-dev tox -e ${{ matrix.python-version }}

      - name: Build wheel
        run: uv build --wheel

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: ci-sdist
          path: dist/*.tar.gz

  publish:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    needs: [test, build_sdist]
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          pattern: ci-*
          path: dist
          merge-multiple: true
      - name: Publish wheels to test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
      # - name: Publish all wheels to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
